#!/bin/bash
#SBATCH -J PancreasAll
#SBATCH -p LKEBgpu
#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=64GB
#SBATCH --gres=gpu:RTX6000:1
#SBATCH --error=/home/smaijer/logs/all/511/job.%J.err
#SBATCH --output=/home/smaijer/logs/all/511/job.%J.out
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=susy.maijer@lumc.nl

# Prepare nnUnet
echo "Starting at Fri Sep 30 20:19:52 CEST 2022"

echo "Running on hosts: $SLURM_JOB_NODELIST"
echo "Running on $SLURM_JOB_NUM_NODES nodes."
echo "Running $SLURM_NTASKS tasks."
echo "CPUs on node: $SLURM_CPUS_ON_NODE."
echo "Account: $SLURM_JOB_ACCOUNT"
echo "Job ID: $SLURM_JOB_ID"
echo "Job name: $SLURM_JOB_NAME"
echo "Node running script: $SLURMD_NODENAME"
echo "Submit host: $SLURM_SUBMIT_HOST"
echo "GPUS: $CUDA_VISIBLE_DEVICES or $SLURM_STEP_GPUS"
nvidia-smi
echo "Current working directory is /home/smaijer"

echo Load all modules..
module purge
module add system/python/3.10.2
echo Done with loading all modules. Modules:
module li
echo Activate conda env nnunet..
source /exports/lkeb-hpc/smaijer/venv_environments/pancreasThesis/bin/activate
echo Verifying environment variables:
conda env config vars list
echo Installing hidden layer and nnUnet..
python -m pip install --upgrade git+https://github.com/FabianIsensee/hiddenlayer.git@more_plotted_details#egg=hiddenlayer
python -m pip install -editable /home/smaijer/code/nnUNet


#nnUNet_determine_postprocessing -t 511 -m 3d_fullres -tr nnUNetTrainerV2 -pl AMOS

echo Done postprocessing! Now start inferencing its own train and test files.
mkdir -p /exports/lkeb-hpc/smaijer/output/511/3d_fullres/nnUNetTrainerV2_AMOS/600/imagesTr
mkdir -p /exports/lkeb-hpc/smaijer/output/511/3d_fullres/nnUNetTrainerV2_AMOS/600/imagesTs
nnUNet_predict -i /exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_raw_data/Task600/imagesTr -o /exports/lkeb-hpc/smaijer/output/511/3d_fullres/nnUNetTrainerV2_AMOS/600/imagesTr -t 511 -m 3d_fullres -tr nnUNetTrainerV2 -p AMOS
nnUNet_predict -i /exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_raw_data/Task600/imagesTs -o /exports/lkeb-hpc/smaijer/output/511/3d_fullres/nnUNetTrainerV2_AMOS/600/imagesTs -t 511 -m 3d_fullres -tr nnUNetTrainerV2 -p AMOS

echo Done inferencing! Now start the evaluation.
nnUNet_evaluate_folder -ref /exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_raw_data/Task600/labelsTr -pred /exports/lkeb-hpc/smaijer/output/511/3d_fullres/nnUNetTrainerV2_AMOS/600/imagesTr -l 1
nnUNet_evaluate_folder -ref /exports/lkeb-hpc/smaijer/data/nnUNet_raw_data_base/nnUNet_raw_data/Task600/labelsTs -pred /exports/lkeb-hpc/smaijer/output/511/3d_fullres/nnUNetTrainerV2_AMOS/600/imagesTs -l 1

echo "Program finished with exit code 0 at: Fri Sep 30 20:19:52 CEST 2022"
